### ISSUE TITLE
Error happened when using ks_gpu  to run a certain data

### ISSUE THREAD

**Issue by PinkCrow007** [TheDatumOrg/kshape-python#13]
When I implemented
```
n1=np.zeros((20, 1440))
n2=np.full((30, 1440), 614631)
n3=np.concatenate((n1,n2),axis=0)
univariate_ts_datasets = np.expand_dims(n3, axis=2)
gpu_model = ks_gpu(univariate_ts_datasets, 3, centroid_init='zero', max_iter=100)
```

I got error:
```
Intel MKL ERROR: Parameter 4 was incorrect on entry to SLASCL.

Intel MKL ERROR: Parameter 4 was incorrect on entry to SLASCL.
info: 89
, submat: 0
info: 1531
Traceback (most recent call last):
  File "D:/apps_data/attempt/k-shape.py", line 279, in <module>
    gpu_model = ks_gpu(univariate_ts_datasets, num_clusters, centroid_init='zero', max_iter=100)
  File "D:\apps_home\Download\anaconda\envs\pytorch\lib\site-packages\kshape\core_gpu.py", line 116, in kshape
    idx, centroids = _kshape(x, k, centroid_init=centroid_init, max_iter=max_iter)
  File "D:\apps_home\Download\anaconda\envs\pytorch\lib\site-packages\kshape\core_gpu.py", line 100, in _kshape
    centroids[j] = torch.unsqueeze(_extract_shape(idx, x, j, centroids[j]), dim=1)
  File "D:\apps_home\Download\anaconda\envs\pytorch\lib\site-packages\kshape\core_gpu.py", line 76, in _extract_shape
    _, vec = torch.symeig(m, eigenvectors=True)
RuntimeError: symeig_cuda: the algorithm failed to converge; 1531 off-diagonal elements of an intermediate tridiagonal form did not converge to zero.

Process finished with exit code 1
```
It seems that ` y = zscore(a, axis=1, ddof=1)` in `core_gpu.py`, line 67   got some huge elements, and `s = y[:, :, 0].transpose(0, 1).mm(y[:, :, 0])` , line 69   got values containing `inf`.

ks_cpu can deal with this dataset successfully.

I use Python 3.7, Pytorch 1.8.0.

**Comment by bogireddytejareddy** [comment]
I believe, for the data you are using, zscore function for gpu version is generating NaN values because of division by zero. I fixed the code to handle NaN for GPU. It should be working now.
